// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/elialombardi/spending-tracker/api-go/spending-tracker.go/internal/db"
	"github.com/elialombardi/spending-tracker/api-go/spending-tracker.go/internal/services"
	"github.com/elialombardi/spending-tracker/api-go/spending-tracker.go/reports"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() (*AppContainer, error) {
	gormDB, err := db.NewDatabase()
	if err != nil {
		return nil, err
	}
	projectTaskService := services.NewProjectTaskService(gormDB)
	locationService := services.NewLocationService(gormDB)
	transactionService := reports.NewTransactionService(gormDB)
	transactionHandler := reports.NewTransactionHandler(transactionService)
	appContainer := &AppContainer{
		DB:                 gormDB,
		ProjectTaskService: projectTaskService,
		LocationService:    locationService,
		TransactionHandler: transactionHandler,
	}
	return appContainer, nil
}

// wire.go:

type AppContainer struct {
	DB                 *gorm.DB
	ProjectTaskService *services.ProjectTaskService
	LocationService    *services.LocationService
	TransactionHandler *reports.TransactionHandler
}
